# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.4-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          PGPASSWORD: ""
          NODE_ENV: test
          PAGER: cat
          RAILS_ENV: test
          TZ: /usr/share/zoneinfo/US/Eastern
          DISABLE_SPRING: true
      - image: cimg/postgres:11.12
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: cimg/redis:6.2.6

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v3-dependencies-

      - run:
          name: Force bundler version to match Gemfile.lock
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler -v=$BUNDLER_VERSION --no-document

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v3-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: cd spec/dummy && bundle exec rake db:create db:schema:load

      - run:
          name: Run apt-get update and install chrome dependencies
          command: |
            sudo apt-get update -y
            sudo apt install libu2f-udev
      - browser-tools/install-chrome:
          replace-existing: false
          chrome-version: "116.0.5845.140"
      - browser-tools/install-chromedriver
      - run:
          name: Check browser tools
          command: |
            google-chrome --version
            chromedriver --version

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
