ruby_version: ruby-2.1.6
bundler_version: 1.14.6
environment:
  RAILS_LOG_LEVEL: '2'
coverage: true
timeout: 300
test_pattern:
  - spec/**_spec.rb
test_exclude_pattern:
  - none
skip_package:
  - ruby
hooks:
  pre_setup: gem install bundler -v 1.14.6 && bundle install --path=$HOME/bundle --no-deployment
  worker_setup: cd spec/dummy && bundle exec rake db:create db:schema:load
